services:
  # Backend API
  - type: web
    name: nexa-mvp-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: CORS_ORIGIN
        value: https://nexa-mvp-frontend.onrender.com

  # Frontend
  - type: static
    name: nexa-mvp-frontend
    plan: starter
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://nexa-mvp-backend.onrender.com
      - key: NODE_VERSION
        value: "18"

databases:
  - name: nexa-mvp-db
    databaseName: nexa_mvp
    plan: starter
    ipAllowList: []
