# Render Blueprint for Constructora E2E Platform
# This is a Node.js/TypeScript project, NOT Python

services:
  - type: web
    name: constructora-web
    env: node
    rootDir: apps/web
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    plan: starter

  - type: web
    name: constructora-api
    env: node
    rootDir: apps/api
    buildCommand: "npm install && npm run prisma:generate && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /healthz
    autoDeploy: true
    plan: starter

  - type: worker
    name: constructora-worker
    env: node
    rootDir: apps/worker
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    plan: starter

databases:
  - name: constructora-db
    plan: starter

servicesPlus:
  - type: redis
    name: constructora-redis
    plan: starter

# Force Node.js environment
env: node
