services:
  - type: web
    name: nexa-mvp-backend
    env: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: wsgi.py
      - key: DATABASE_URL
        fromDatabase:
          name: nexa-mvp-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"

  - type: web
    name: nexa-mvp-frontend
    env: static
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: REACT_APP_API_URL
        fromService:
          name: nexa-mvp-backend
          type: web
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: nexa-mvp-db
    databaseName: nexa_mvp
    user: nexa_mvp_user
    plan: starter
